/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EXCEL;

/**
 *
 * @author luisg
 */
public class Evaluacion extends javax.swing.JFrame {

    /**
     * Creates new form Evaluacion
     */
    
    public static int gRequisitos = 0;
    public static int pProyectos = 0;
    public static int asegCalidad = 0;
    public static int desReq = 0;
    public static int verificacion = 0;
    public static int gRiesgos = 0;
    public static int aProcesos = 0;
    public static int gCProyectos = 0;
    
    
    public Evaluacion() {
        initComponents();
        introduccion.setText("<html>A continuación se facilitan las respuestas otorgadas por la persona/s encargadas en la PYME para facilitarnos la información necesaria. A partir de dichas respuestas se calcularán los resultados obtenidos para la evaluación.<html>");
//        gestionDeRequisitos.setText("<html>Gestion de requisitos \n Categoria: Ingenieria<html>");
//        planificacionDeProyectos.setText("<html>Planificacion de <br> Proyectos <br> categoria: <br> gestion de proyectos");
        jlGRequisitos.setText(gRequisitos+"/70");
        jlPlaniProyectos.setText(pProyectos+"/125");
        jlAsegCalidad.setText(asegCalidad+"/70");
        jldesReq.setText(desReq+"/110");
        jlVerificacion.setText(verificacion+"/100");
        jlGRiesgo.setText(gRiesgos+"/95");
        jlAProcesos.setText(aProcesos+"/85");
        jlGCPorye.setText(gCProyectos+"/95");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        introduccion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gestionDeRequisitos = new javax.swing.JButton();
        planificacionDeProyectos = new javax.swing.JButton();
        gestionDeRequisitos3 = new javax.swing.JButton();
        gestionDeRequisitos4 = new javax.swing.JButton();
        gestionDeRequisitos5 = new javax.swing.JButton();
        gestionDeRequisitos6 = new javax.swing.JButton();
        jbVerificacion = new javax.swing.JButton();
        gestionDeRequisitos8 = new javax.swing.JButton();
        jlGRequisitos = new javax.swing.JLabel();
        jlPlaniProyectos = new javax.swing.JLabel();
        jlAsegCalidad = new javax.swing.JLabel();
        jldesReq = new javax.swing.JLabel();
        jlVerificacion = new javax.swing.JLabel();
        jlGRiesgo = new javax.swing.JLabel();
        jlAProcesos = new javax.swing.JLabel();
        jlGCPorye = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel1.setText("Modelo de Madures CMM");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel2.setText("Introducción");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel3.setText("Categorias:");

        gestionDeRequisitos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gestionDeRequisitos.setText("<html>Gestion de Requisitos\ncategoria:\ningenieria<html>");
        gestionDeRequisitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionDeRequisitosMouseClicked(evt);
            }
        });
        gestionDeRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionDeRequisitosActionPerformed(evt);
            }
        });

        planificacionDeProyectos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        planificacionDeProyectos.setText("<html>\nPlanificacion de proyectos\nGestion de proyectos\n<html>\n   ");
        planificacionDeProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planificacionDeProyectosActionPerformed(evt);
            }
        });

        gestionDeRequisitos3.setText("<html>\ndesarrollo de requisitos\ncategoria: ingenieria\n<html>\n");
        gestionDeRequisitos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionDeRequisitos3ActionPerformed(evt);
            }
        });

        gestionDeRequisitos4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gestionDeRequisitos4.setText("<html>\nGestion de riesgos\nCategoria: Gestion de proyectos\n<html>");
        gestionDeRequisitos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionDeRequisitos4ActionPerformed(evt);
            }
        });

        gestionDeRequisitos5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gestionDeRequisitos5.setText("<html>\nAseguramiento de la calidad\nCategoria: Soporte\n<html>");
        gestionDeRequisitos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionDeRequisitos5ActionPerformed(evt);
            }
        });

        gestionDeRequisitos6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gestionDeRequisitos6.setText("<html>\nAnálisis de Procesos Organizativos\nCategoria: analisis de proceso\n<html>");
        gestionDeRequisitos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionDeRequisitos6ActionPerformed(evt);
            }
        });

        jbVerificacion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbVerificacion.setText("<html>\nVerificacion\nCategoria: Ingenieria\n<html>");
        jbVerificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerificacionActionPerformed(evt);
            }
        });

        gestionDeRequisitos8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gestionDeRequisitos8.setText("<html>\n Gestión Cuantitativa de Proyectos\nCategoria: gestion de proyectos\n<html>");
        gestionDeRequisitos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionDeRequisitos8ActionPerformed(evt);
            }
        });

        jlPlaniProyectos.setText("jLabel4");

        jlAsegCalidad.setText("n");

        jldesReq.setText("jLabel4");

        jlVerificacion.setText("jLabel4");

        jlGRiesgo.setText("jLabel4");

        jlAProcesos.setText("jLabel4");

        jlGCPorye.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(planificacionDeProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gestionDeRequisitos3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gestionDeRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(gestionDeRequisitos5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gestionDeRequisitos4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gestionDeRequisitos6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gestionDeRequisitos8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(introduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jlGRequisitos)
                .addGap(180, 180, 180)
                .addComponent(jlAsegCalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(jlVerificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlAProcesos)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jlPlaniProyectos)
                .addGap(145, 145, 145)
                .addComponent(jldesReq)
                .addGap(143, 143, 143)
                .addComponent(jlGRiesgo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlGCPorye)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(introduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gestionDeRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gestionDeRequisitos5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gestionDeRequisitos6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGRequisitos)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlAsegCalidad)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlAProcesos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gestionDeRequisitos3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gestionDeRequisitos4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(planificacionDeProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gestionDeRequisitos8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlVerificacion)
                                .addGap(129, 129, 129)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPlaniProyectos)
                            .addComponent(jldesReq)
                            .addComponent(jlGRiesgo)
                            .addComponent(jlGCPorye))
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionDeRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionDeRequisitosActionPerformed
        // TODO add your handling code here:
        gRequisitos ventana = new gRequisitos();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionDeRequisitosActionPerformed

    private void planificacionDeProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planificacionDeProyectosActionPerformed
        // TODO add your handling code here:
        pProyectos pp = new pProyectos();
        pp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_planificacionDeProyectosActionPerformed

    private void gestionDeRequisitos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionDeRequisitos3ActionPerformed
        // TODO add your handling code here:

        DesarrolloRequisitos dr = new DesarrolloRequisitos();
        dr.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_gestionDeRequisitos3ActionPerformed

    private void gestionDeRequisitos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionDeRequisitos4ActionPerformed
        // TODO add your handling code here:
        GestionRiesgo gr = new GestionRiesgo();
        gr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionDeRequisitos4ActionPerformed

    private void gestionDeRequisitos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionDeRequisitos5ActionPerformed
        // TODO add your handling code here:
        aseguramientoCalidad asegC = new aseguramientoCalidad();
        asegC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionDeRequisitos5ActionPerformed

    private void gestionDeRequisitos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionDeRequisitos6ActionPerformed
        // TODO add your handling code here:
        AnalisisDeProcesos ap = new AnalisisDeProcesos();
        ap.setVisible(true);
        this .dispose();
        
        
        
    }//GEN-LAST:event_gestionDeRequisitos6ActionPerformed

    private void jbVerificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerificacionActionPerformed
        // TODO add your handling code here:
        Verificacion v = new Verificacion();
        v.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jbVerificacionActionPerformed

    private void gestionDeRequisitos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionDeRequisitos8ActionPerformed
        // TODO add your handling code here:
        GCProyectos gc = new GCProyectos();
        gc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_gestionDeRequisitos8ActionPerformed

    private void gestionDeRequisitosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionDeRequisitosMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_gestionDeRequisitosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        System.out.println(gRequisitos);
        System.out.println(pProyectos);
        jlGRequisitos.setText(gRequisitos+"/70");
        jlPlaniProyectos.setText(pProyectos+"/125");
        jlAsegCalidad.setText(asegCalidad+"/70");
        jldesReq.setText(desReq+"/110");
        jlVerificacion.setText(verificacion+"/100");
        jlGRiesgo.setText(gRiesgos+"/95");
        jlAProcesos.setText(aProcesos+"/85");
        jlGCPorye.setText(gCProyectos+"/95");

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gestionDeRequisitos;
    private javax.swing.JButton gestionDeRequisitos3;
    private javax.swing.JButton gestionDeRequisitos4;
    private javax.swing.JButton gestionDeRequisitos5;
    private javax.swing.JButton gestionDeRequisitos6;
    private javax.swing.JButton gestionDeRequisitos8;
    private javax.swing.JLabel introduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbVerificacion;
    private javax.swing.JLabel jlAProcesos;
    private javax.swing.JLabel jlAsegCalidad;
    private javax.swing.JLabel jlGCPorye;
    private javax.swing.JLabel jlGRequisitos;
    private javax.swing.JLabel jlGRiesgo;
    private javax.swing.JLabel jlPlaniProyectos;
    private javax.swing.JLabel jlVerificacion;
    private javax.swing.JLabel jldesReq;
    private javax.swing.JButton planificacionDeProyectos;
    // End of variables declaration//GEN-END:variables
}
